/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qatarproject;

import java.sql.*;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 *
 *
 *
 * /**
 *
 * @author Christian
 */
public class Match extends javax.swing.JFrame {

    /**
     * Creates new form Match
     */
    public Match() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        EquipoB1 = new javax.swing.JTextField();
        EquipoA1 = new javax.swing.JTextField();
        GolA1 = new javax.swing.JTextField();
        GolB1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        EquipoB2 = new javax.swing.JTextField();
        EquipoA2 = new javax.swing.JTextField();
        GolA2 = new javax.swing.JTextField();
        GolB2 = new javax.swing.JTextField();
        EquipoB3 = new javax.swing.JTextField();
        EquipoA3 = new javax.swing.JTextField();
        GolA3 = new javax.swing.JTextField();
        GolB3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EquipoB4 = new javax.swing.JTextField();
        EquipoA4 = new javax.swing.JTextField();
        GolA4 = new javax.swing.JTextField();
        GolB4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        GolB5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        EquipoB5 = new javax.swing.JTextField();
        EquipoA5 = new javax.swing.JTextField();
        GolA5 = new javax.swing.JTextField();
        GolB6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        EquipoB6 = new javax.swing.JTextField();
        EquipoA6 = new javax.swing.JTextField();
        GolA6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Match 1:");

        GolA1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GolA1KeyTyped(evt);
            }
        });

        GolB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GolB1ActionPerformed(evt);
            }
        });
        GolB1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GolB1KeyTyped(evt);
            }
        });

        jLabel2.setText("Match 2:");

        GolA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GolA2ActionPerformed(evt);
            }
        });
        GolA2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GolA2KeyTyped(evt);
            }
        });

        GolB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GolB2ActionPerformed(evt);
            }
        });
        GolB2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GolB2KeyTyped(evt);
            }
        });

        GolA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GolA3ActionPerformed(evt);
            }
        });
        GolA3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GolA3KeyTyped(evt);
            }
        });

        GolB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GolB3ActionPerformed(evt);
            }
        });
        GolB3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GolB3KeyTyped(evt);
            }
        });

        jLabel3.setText("Match 3:");

        GolA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GolA4ActionPerformed(evt);
            }
        });
        GolA4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GolA4KeyTyped(evt);
            }
        });

        GolB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GolB4ActionPerformed(evt);
            }
        });
        GolB4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GolB4KeyTyped(evt);
            }
        });

        jLabel4.setText("Match 4:");

        GolB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GolB5ActionPerformed(evt);
            }
        });
        GolB5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GolB5KeyTyped(evt);
            }
        });

        jLabel5.setText("Match 5:");

        GolA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GolA5ActionPerformed(evt);
            }
        });
        GolA5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GolA5KeyTyped(evt);
            }
        });

        GolB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GolB6ActionPerformed(evt);
            }
        });
        GolB6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GolB6KeyTyped(evt);
            }
        });

        jLabel6.setText("Match 6:");

        GolA6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GolA6ActionPerformed(evt);
            }
        });
        GolA6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GolA6KeyTyped(evt);
            }
        });

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(EquipoA6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(GolA6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(EquipoB6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(GolB6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(EquipoA3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(GolA3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(EquipoB3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(GolB3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(EquipoA2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(GolA2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(EquipoB2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(GolB2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(EquipoA1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(GolA1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(EquipoB1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(GolB1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1)))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EquipoA4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GolA4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EquipoB4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GolB4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EquipoA5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GolA5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EquipoB5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GolB5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EquipoA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GolA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EquipoB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GolB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EquipoA4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GolA4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EquipoB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GolB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EquipoA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GolA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EquipoB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GolB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EquipoA5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GolA5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EquipoB5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GolB5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EquipoA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GolA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EquipoB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GolB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EquipoA6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GolA6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EquipoB6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GolB6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Datos Equipos A Selecciones
        String A1 = EquipoA1.getText();
        String A2 = EquipoA2.getText();
        String A3 = EquipoA3.getText();
        String A4 = EquipoA4.getText();
        String A5 = EquipoA5.getText();
        String A6 = EquipoA6.getText();

        //Datos Equipos A Goles
        String GA1 = GolA1.getText();
        String GA2 = GolA2.getText();
        String GA3 = GolA3.getText();
        String GA4 = GolA4.getText();
        String GA5 = GolA5.getText();
        String GA6 = GolA6.getText();

        //Datos Equipos B
        String B1 = EquipoB1.getText();
        String B2 = EquipoB2.getText();
        String B3 = EquipoB3.getText();
        String B4 = EquipoB4.getText();
        String B5 = EquipoB5.getText();
        String B6 = EquipoB6.getText();

        //Datos Equipos A Goles
        String GB1 = GolB1.getText();
        String GB2 = GolB2.getText();
        String GB3 = GolB3.getText();
        String GB4 = GolB4.getText();
        String GB5 = GolB5.getText();
        String GB6 = GolB6.getText();

        
        //valida que todas las selecciones esten ingresadas
        if (A1.isEmpty() || A2.isEmpty() || A3.isEmpty() || A4.isEmpty() || A5.isEmpty() || A6.isEmpty() ||
                B1.isEmpty() || B2.isEmpty() || B3.isEmpty() || B4.isEmpty() || B5.isEmpty() || B6.isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe rellenar TODAS las selecciones");
            System.exit(0);
        }
        //valida que todos los marcadores esten colocados
        if (GA1.isEmpty() || GA2.isEmpty() || GA3.isEmpty() || GA4.isEmpty() || GA5.isEmpty() || GA6.isEmpty() ||
                GB1.isEmpty() || GB2.isEmpty() || GB3.isEmpty() || GB4.isEmpty() || GB5.isEmpty() || GB6.isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe rellenar TODOS los marcadores");
            System.exit(0);
        }
                  
        
        try {
            Connection con = Conexion.getConexion();
            Statement st;
            st = con.createStatement();
            
            //Consultas para insertar datos a la dba
            st.executeUpdate("INSERT INTO Partido(IdPartido,EquipoA,EquipoB,GolA,GolB,Ganador) VALUES(1,'" + A1 + "', '" + B1 + "', " + GA1 + "," + GB1 + "," + "'" + A1 + "')");
            st.executeUpdate("INSERT INTO Partido(IdPartido,EquipoA,EquipoB,GolA,GolB,Ganador) VALUES(2,'" + A2 + "', '" + B2 + "', " + GA2 + "," + GB2 + "," + "'" + A2 + "')");
            st.executeUpdate("INSERT INTO Partido(IdPartido,EquipoA,EquipoB,GolA,GolB,Ganador) VALUES(3,'" + A3 + "', '" + B3 + "', " + GA3 + "," + GB3 + "," + "'" + A3 + "')");
            st.executeUpdate("INSERT INTO Partido(IdPartido,EquipoA,EquipoB,GolA,GolB,Ganador) VALUES(4,'" + A4 + "', '" + B4 + "', " + GA4 + "," + GB4 + "," + "'" + A4 + "')");
            st.executeUpdate("INSERT INTO Partido(IdPartido,EquipoA,EquipoB,GolA,GolB,Ganador) VALUES(5,'" + A5 + "', '" + B5 + "', " + GA5 + "," + GB5 + "," + "'" + A5 + "')");
            st.executeUpdate("INSERT INTO Partido(IdPartido,EquipoA,EquipoB,GolA,GolB,Ganador) VALUES(6,'" + A6 + "', '" + B6 + "', " + GA6 + "," + GB6 + "," + "'" + A6 + "')");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void GolA1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GolA1KeyTyped
        char a = evt.getKeyChar();
        
        if (!Character.isDigit(a)) {
            evt.consume();   
        }
    }//GEN-LAST:event_GolA1KeyTyped

    private void GolB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GolB1ActionPerformed

    }//GEN-LAST:event_GolB1ActionPerformed

    private void GolA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GolA2ActionPerformed

    }//GEN-LAST:event_GolA2ActionPerformed

    private void GolB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GolB2ActionPerformed

    }//GEN-LAST:event_GolB2ActionPerformed

    private void GolA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GolA3ActionPerformed

    }//GEN-LAST:event_GolA3ActionPerformed

    private void GolB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GolB3ActionPerformed

    }//GEN-LAST:event_GolB3ActionPerformed

    private void GolA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GolA4ActionPerformed

    }//GEN-LAST:event_GolA4ActionPerformed

    private void GolB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GolB4ActionPerformed

    }//GEN-LAST:event_GolB4ActionPerformed

    private void GolA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GolA5ActionPerformed

    }//GEN-LAST:event_GolA5ActionPerformed

    private void GolB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GolB5ActionPerformed

    }//GEN-LAST:event_GolB5ActionPerformed

    private void GolA6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GolA6ActionPerformed

    }//GEN-LAST:event_GolA6ActionPerformed

    private void GolB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GolB6ActionPerformed

    }//GEN-LAST:event_GolB6ActionPerformed

    private void GolB1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GolB1KeyTyped
        char a = evt.getKeyChar();
        
        if (!Character.isDigit(a)) {
            evt.consume();   
        }
    }//GEN-LAST:event_GolB1KeyTyped

    private void GolA2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GolA2KeyTyped
        char a = evt.getKeyChar();
        
        if (!Character.isDigit(a)) {
            evt.consume();   
        }
    }//GEN-LAST:event_GolA2KeyTyped

    private void GolB2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GolB2KeyTyped
        char a = evt.getKeyChar();
        
        if (!Character.isDigit(a)) {
            evt.consume();   
        }
    }//GEN-LAST:event_GolB2KeyTyped

    private void GolA3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GolA3KeyTyped
        char a = evt.getKeyChar();
        
        if (!Character.isDigit(a)) {
            evt.consume();   
        }
    }//GEN-LAST:event_GolA3KeyTyped

    private void GolB3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GolB3KeyTyped
        char a = evt.getKeyChar();
        
        if (!Character.isDigit(a)) {
            evt.consume();   
        }
    }//GEN-LAST:event_GolB3KeyTyped

    private void GolA4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GolA4KeyTyped
        char a = evt.getKeyChar();
        
        if (!Character.isDigit(a)) {
            evt.consume();   
        }
    }//GEN-LAST:event_GolA4KeyTyped

    private void GolB4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GolB4KeyTyped
        char a = evt.getKeyChar();
        
        if (!Character.isDigit(a)) {
            evt.consume();   
        }
    }//GEN-LAST:event_GolB4KeyTyped

    private void GolA5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GolA5KeyTyped
        char a = evt.getKeyChar();
        
        if (!Character.isDigit(a)) {
            evt.consume();   
        }
    }//GEN-LAST:event_GolA5KeyTyped

    private void GolB5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GolB5KeyTyped
        char a = evt.getKeyChar();
        
        if (!Character.isDigit(a)) {
            evt.consume();   
        }
    }//GEN-LAST:event_GolB5KeyTyped

    private void GolA6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GolA6KeyTyped
        char a = evt.getKeyChar();
        
        if (!Character.isDigit(a)) {
            evt.consume();   
        }
    }//GEN-LAST:event_GolA6KeyTyped

    private void GolB6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GolB6KeyTyped
        char a = evt.getKeyChar();
        
        if (!Character.isDigit(a)) {
            evt.consume();   
        }
    }//GEN-LAST:event_GolB6KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Match.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Match.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Match.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Match.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Match().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EquipoA1;
    private javax.swing.JTextField EquipoA2;
    private javax.swing.JTextField EquipoA3;
    private javax.swing.JTextField EquipoA4;
    private javax.swing.JTextField EquipoA5;
    private javax.swing.JTextField EquipoA6;
    private javax.swing.JTextField EquipoB1;
    private javax.swing.JTextField EquipoB2;
    private javax.swing.JTextField EquipoB3;
    private javax.swing.JTextField EquipoB4;
    private javax.swing.JTextField EquipoB5;
    private javax.swing.JTextField EquipoB6;
    private javax.swing.JTextField GolA1;
    private javax.swing.JTextField GolA2;
    private javax.swing.JTextField GolA3;
    private javax.swing.JTextField GolA4;
    private javax.swing.JTextField GolA5;
    private javax.swing.JTextField GolA6;
    private javax.swing.JTextField GolB1;
    private javax.swing.JTextField GolB2;
    private javax.swing.JTextField GolB3;
    private javax.swing.JTextField GolB4;
    private javax.swing.JTextField GolB5;
    private javax.swing.JTextField GolB6;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
